# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '27-响应式编程' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #  use_frameworks!

  # Pods for 27-响应式编程
  pod 'RxSwift', '~>5'
  pod 'RxCocoa', '~>5'

end
