# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Business' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'INTULocationManager'
#  pod 'BaiduMapKit'
  pod 'JPush'
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCAnalytics'
  pod 'UMCShare/UI'
  pod 'UMCShare/Social/WeChat'
  pod 'UMCShare/Social/AlipayShare'
#  pod 'WoodPeckeriOS'
  pod 'FMDB'
#  pod 'OOMDetector'
  pod 'WebViewJavascriptBridge'
  # Pods for Business

end
