# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '29-项目实战' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 29-项目实战
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'KakaJSON'
  pod 'KingfisherWebP'
  
end
