# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Our Planet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Our Planet
  pod 'RxSwift',    '~> 3.2'
  pod 'RxCocoa',    '~> 3.2'
  
end
